function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

// ---------------------------------------------------------------------------
// Lifecycle Walkthrough: Mermaid.js flow diagram + Next/Prev stepper.
// Data comes from the #lifecycle-data JSON script tag (only present on
// index.html), generated by build.py from the COURSE_LIFECYCLE list.
// ---------------------------------------------------------------------------
let lifecycleData = [];
let currentStep = 0;

function readLifecycleData() {
  const host = document.getElementById('lifecycle-data');
  if (!host) {
    return [];
  }
  try {
    return JSON.parse(host.textContent);
  } catch (error) {
    return [];
  }
}

// Extra "input" hand-offs called out explicitly in each day's `connects` text
// that skip ahead of the plain day-by-day sequence (for example, Day 4's
// pain points feed both Day 5 AND Week 2 Day 3's heuristic audit). Each entry
// is [fromWeekId, fromAnchor, toWeekId, toAnchor].
const LIFECYCLE_EXTRA_EDGES = [
  ['week1', 'd1', 'week2', 'd4'],
  ['week1', 'd2', 'week1', 'd4'],
  ['week1', 'd3', 'week3', 'd1'],
  ['week1', 'd4', 'week2', 'd3'],
  ['week2', 'd2', 'week3', 'd2'],
  ['week2', 'd3', 'week2', 'd5'],
  ['week2', 'd3', 'week3', 'd1'],
  ['week2', 'd4', 'week3', 'd1'],
  ['week2', 'd5', 'week3', 'd2'],
];

function findLifecycleIndex(weekId, anchor) {
  return lifecycleData.findIndex((day) => day.week_id === weekId && day.anchor === anchor);
}

function buildLifecycleEdges() {
  const edges = [];
  for (let idx = 0; idx < lifecycleData.length - 1; idx += 1) {
    edges.push([idx, idx + 1]);
  }
  LIFECYCLE_EXTRA_EDGES.forEach(([fromWeek, fromAnchor, toWeek, toAnchor]) => {
    const from = findLifecycleIndex(fromWeek, fromAnchor);
    const to = findLifecycleIndex(toWeek, toAnchor);
    if (from !== -1 && to !== -1) {
      edges.push([from, to]);
    }
  });
  return edges;
}

function buildMermaidDefinition(activeIndex) {
  const lines = ['flowchart TD'];
  lines.push('classDef w1 fill:#1a1b1e,stroke:#8a8f98,color:#f3f3f2;');
  lines.push('classDef w2 fill:#1e1213,stroke:#7a1218,color:#f3f3f2;');
  lines.push('classDef w3 fill:#22100f,stroke:#e2001a,color:#f3f3f2;');
  lines.push('classDef w4 fill:#1c1c1c,stroke:#f3f3f2,color:#f3f3f2;');
  lines.push('classDef activeStep stroke:#ff3b30,stroke-width:5px,font-weight:700;');
  lines.push('classDef dimmed fill:#131315,stroke:#2b2b2f,color:#5a5a60;');

  const byWeek = {};
  lifecycleData.forEach((day, idx) => {
    if (!byWeek[day.week_id]) {
      byWeek[day.week_id] = [];
    }
    byWeek[day.week_id].push({ ...day, idx });
  });

  Object.keys(byWeek).forEach((weekId) => {
    const days = byWeek[weekId];
    lines.push(`subgraph ${weekId}_sg["${escapeHtml(days[0].week_label)} - ${escapeHtml(days[0].week_theme)}"]`);
    days.forEach((day) => {
      const nodeId = `N${day.idx + 1}`;
      const label = `${escapeHtml(day.week_label)} ${escapeHtml(day.day)}<br/>${escapeHtml(day.title)}`;
      lines.push(`${nodeId}["${label}"]`);
    });
    lines.push('end');
  });

  const edges = buildLifecycleEdges();
  edges.forEach(([from, to]) => {
    lines.push(`N${from + 1} --> N${to + 1}`);
  });

  // Only the active node's direct inputs (predecessors) and direct hand-offs
  // (successors) stay lit up; every other node/edge fades into the background.
  const litNodes = new Set([activeIndex]);
  const litEdgeIdxs = [];
  edges.forEach(([from, to], edgeIdx) => {
    if (from === activeIndex || to === activeIndex) {
      litNodes.add(from);
      litNodes.add(to);
      litEdgeIdxs.push(edgeIdx);
    }
  });

  Object.keys(byWeek).forEach((weekId) => {
    const litIds = byWeek[weekId].filter((day) => litNodes.has(day.idx)).map((day) => `N${day.idx + 1}`);
    const dimIds = byWeek[weekId].filter((day) => !litNodes.has(day.idx)).map((day) => `N${day.idx + 1}`);
    if (litIds.length) {
      lines.push(`class ${litIds.join(',')} ${weekId}`);
    }
    if (dimIds.length) {
      lines.push(`class ${dimIds.join(',')} dimmed`);
    }
  });

  lines.push(`class N${activeIndex + 1} activeStep`);

  const dimEdgeIdxs = edges.map((_, edgeIdx) => edgeIdx).filter((edgeIdx) => !litEdgeIdxs.includes(edgeIdx));
  if (dimEdgeIdxs.length) {
    lines.push(`linkStyle ${dimEdgeIdxs.join(',')} stroke:#2b2b2f,stroke-width:1px,opacity:0.3;`);
  }
  if (litEdgeIdxs.length) {
    lines.push(`linkStyle ${litEdgeIdxs.join(',')} stroke:#ff3b30,stroke-width:3px,opacity:1;`);
  }

  lifecycleData.forEach((_, idx) => {
    lines.push(`click N${idx + 1} lifecycleNodeClick`);
  });

  return lines.join('\n');
}

async function renderLifecycleDiagram() {
  const container = document.getElementById('lifecycle-mermaid');
  if (!container || !window.mermaid) {
    return;
  }
  const definition = buildMermaidDefinition(currentStep);
  try {
    const { svg, bindFunctions } = await window.mermaid.render('lifecycleGraph', definition);
    container.innerHTML = svg;
    if (bindFunctions) {
      bindFunctions(container);
    }
  } catch (error) {
    container.innerHTML = '<p>Diagram could not render.</p>';
  }
}

function renderStepperPanel(index) {
  const panel = document.getElementById('stepper-panel');
  if (!panel) {
    return;
  }
  const day = lifecycleData[index];
  if (!day) {
    return;
  }
  const artifactItems = (day.artifacts || []).map((a) => `<li>${escapeHtml(a)}</li>`).join('');

  panel.innerHTML = `
    <span class="day-kicker">${escapeHtml(day.week_label)} &middot; ${escapeHtml(day.day)}</span>
    <h3 class="stepper-panel-title">${escapeHtml(day.title)}</h3>
    <div class="day-block block-do">
      <h4>What You Do</h4>
      <p>${escapeHtml(day.what)}</p>
    </div>
    <div class="day-block block-why">
      <h4>Why We Do This</h4>
      <p>${escapeHtml(day.why)}</p>
    </div>
    <div class="day-block block-artifacts">
      <h4>Key Artifacts</h4>
      <ul class="day-artifacts">${artifactItems}</ul>
    </div>
    <div class="day-block block-connects day-connects">
      <h4>Connects To</h4>
      <p>${escapeHtml(day.connects)}</p>
    </div>
    <a class="stepper-link" href="${day.link}">Open ${escapeHtml(day.week_label)} Page &rarr;</a>
  `;
}

function updateStepper(index) {
  const total = lifecycleData.length;
  if (total === 0) {
    return;
  }
  currentStep = Math.max(0, Math.min(index, total - 1));

  const progressLabel = document.getElementById('stepper-progress-label');
  if (progressLabel) {
    progressLabel.textContent = `Step ${currentStep + 1} of ${total}`;
  }

  const prevBtn = document.getElementById('stepper-prev');
  const nextBtn = document.getElementById('stepper-next');
  if (prevBtn) {
    prevBtn.disabled = currentStep === 0;
  }
  if (nextBtn) {
    nextBtn.disabled = currentStep === total - 1;
  }

  renderStepperPanel(currentStep);
  renderLifecycleDiagram();
}

window.lifecycleNodeClick = function lifecycleNodeClick(nodeId) {
  const idx = parseInt(String(nodeId).replace('N', ''), 10) - 1;
  if (!Number.isNaN(idx)) {
    updateStepper(idx);
  }
};

function initLifecycleStepper() {
  const stepperHost = document.getElementById('lifecycle-stepper');
  lifecycleData = readLifecycleData();
  if (!stepperHost || lifecycleData.length === 0) {
    return;
  }

  if (window.mermaid) {
    window.mermaid.initialize({
      startOnLoad: false,
      securityLevel: 'loose',
      theme: 'base',
      themeVariables: {
        darkMode: true,
        background: '#0b0b0c',
        primaryColor: '#141416',
        primaryTextColor: '#f3f3f2',
        primaryBorderColor: '#2b2b2f',
        lineColor: '#8a8f98',
        secondaryColor: '#1b1b1e',
        tertiaryColor: '#1b1b1e',
        clusterBkg: '#101012',
        clusterBorder: '#2b2b2f',
        edgeLabelBackground: '#101012',
        fontFamily: 'Space Grotesk, Segoe UI, sans-serif',
        fontSize: '16px',
      },
      flowchart: {
        nodeSpacing: 45,
        rankSpacing: 65,
        padding: 12,
        htmlLabels: true,
      },
    });
  }

  const prevBtn = document.getElementById('stepper-prev');
  const nextBtn = document.getElementById('stepper-next');
  if (prevBtn) {
    prevBtn.addEventListener('click', () => updateStepper(currentStep - 1));
  }
  if (nextBtn) {
    nextBtn.addEventListener('click', () => updateStepper(currentStep + 1));
  }

  updateStepper(0);
}

initLifecycleStepper();
initSampleDialogs();
initSiteMenu();
initGlossaryTerms();
initGlossarySearch();
initScrollProgress();
initDayAccordion();
initJumpNavScrollSpy();
initVisualsTabs();
initMilestoneTabs();
initScrollReveal();

// ---------------------------------------------------------------------------
// Site menu: hamburger toggle for the Core TPM Content / Technical Content
// dropdown in the header (present on every page via base.html).
// ---------------------------------------------------------------------------
function initSiteMenu() {
  const toggleBtn = document.getElementById('menu-toggle-btn');
  const menu = document.getElementById('site-menu');
  if (!toggleBtn || !menu) {
    return;
  }

  function closeMenu() {
    menu.dataset.open = 'false';
    toggleBtn.setAttribute('aria-expanded', 'false');
  }

  function openMenu() {
    menu.dataset.open = 'true';
    toggleBtn.setAttribute('aria-expanded', 'true');
  }

  toggleBtn.addEventListener('click', (event) => {
    event.stopPropagation();
    if (menu.dataset.open === 'true') {
      closeMenu();
    } else {
      openMenu();
    }
  });

  document.addEventListener('click', (event) => {
    if (menu.dataset.open === 'true' && !menu.contains(event.target) && event.target !== toggleBtn) {
      closeMenu();
    }
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      closeMenu();
    }
  });
}

// ---------------------------------------------------------------------------
// Milestone "View Filled Sample" dialogs (index.html only). Opens the native
// <dialog> that matches the clicked button's data-open-dialog id, closes on
// the close button, the Escape key (native), or a click on the backdrop.
// ---------------------------------------------------------------------------
function initSampleDialogs() {
  document.addEventListener('click', (event) => {
    const opener = event.target.closest('[data-open-dialog]');
    if (opener) {
      const dialog = document.getElementById(opener.dataset.openDialog);
      if (dialog && typeof dialog.showModal === 'function') {
        dialog.showModal();
      }
      return;
    }
    const closer = event.target.closest('[data-close-dialog]');
    if (closer) {
      closer.closest('dialog')?.close();
    }
  });

  document.querySelectorAll('dialog.sample-dialog').forEach((dialog) => {
    dialog.addEventListener('click', (event) => {
      if (event.target === dialog) {
        dialog.close();
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Click-to-define glossary terms. Any element with class "gloss-term" (added
// by build.py's glossarize() around known jargon in day cards, diagrams, and
// milestone cards) opens a small popover with a plain-English definition,
// pulled from the #glossary-data JSON script tag (present on every page via
// base.html). Works with mouse (click) and keyboard (Enter/Space, Escape).
// ---------------------------------------------------------------------------
function readGlossaryData() {
  const host = document.getElementById('glossary-data');
  if (!host) {
    return {};
  }
  try {
    return JSON.parse(host.textContent);
  } catch (error) {
    return {};
  }
}

function initGlossaryTerms() {
  const glossary = readGlossaryData();
  const popover = document.getElementById('gloss-popover');
  if (!popover) {
    return;
  }
  const termEl = document.getElementById('gloss-popover-term');
  const defEl = document.getElementById('gloss-popover-def');
  const badgeEl = document.getElementById('gloss-popover-badge');
  const linkEl = document.getElementById('gloss-popover-link');
  const closeBtn = document.getElementById('gloss-popover-close');
  let activeTerm = null;

  function closePopover() {
    popover.hidden = true;
    if (activeTerm) {
      activeTerm.setAttribute('aria-expanded', 'false');
      activeTerm = null;
    }
  }

  function openPopover(target) {
    const id = target.dataset.glossId;
    const entry = glossary[id];
    if (!entry) {
      return;
    }
    if (activeTerm && activeTerm !== target) {
      activeTerm.setAttribute('aria-expanded', 'false');
    }

    const isCore = entry.category === 'core';
    termEl.textContent = entry.term;
    defEl.textContent = entry.definition;
    badgeEl.textContent = isCore ? 'Core TPM Glossary' : 'Technical Glossary';
    badgeEl.className = `gloss-popover-badge ${isCore ? 'badge-core' : 'badge-technical'}`;
    linkEl.href = `${isCore ? 'glossary-core.html' : 'glossary-technical.html'}#term-${id}`;

    popover.hidden = false;
    activeTerm = target;
    target.setAttribute('aria-expanded', 'true');

    const rect = target.getBoundingClientRect();
    const popRect = popover.getBoundingClientRect();
    const viewportWidth = document.documentElement.clientWidth;
    let left = window.scrollX + rect.left;
    const maxLeft = window.scrollX + viewportWidth - popRect.width - 12;
    if (left > maxLeft) {
      left = Math.max(window.scrollX + 12, maxLeft);
    }
    let top = window.scrollY + rect.bottom + 8;
    popover.style.left = `${left}px`;
    popover.style.top = `${top}px`;
  }

  document.addEventListener('click', (event) => {
    const term = event.target.closest('.gloss-term');
    if (term) {
      event.preventDefault();
      if (term === activeTerm && !popover.hidden) {
        closePopover();
      } else {
        openPopover(term);
      }
      return;
    }
    if (!popover.hidden && !popover.contains(event.target)) {
      closePopover();
    }
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      closePopover();
      return;
    }
    if ((event.key === 'Enter' || event.key === ' ') && event.target.classList?.contains('gloss-term')) {
      event.preventDefault();
      openPopover(event.target);
    }
  });

  closeBtn?.addEventListener('click', closePopover);
  window.addEventListener('resize', closePopover);
}

// ---------------------------------------------------------------------------
// Glossary page live search (glossary-core.html / glossary-technical.html).
// Filters .glossary-card elements by term name + definition text.
// ---------------------------------------------------------------------------
function initGlossarySearch() {
  const input = document.getElementById('glossary-search');
  const grid = document.getElementById('glossary-grid');
  const emptyMsg = document.getElementById('glossary-empty');
  if (!input || !grid) {
    return;
  }
  const cards = Array.from(grid.querySelectorAll('.glossary-card'));

  input.addEventListener('input', () => {
    const query = input.value.trim().toLowerCase();
    let visibleCount = 0;
    cards.forEach((card) => {
      const matches = !query || (card.dataset.termName || '').includes(query);
      card.hidden = !matches;
      if (matches) {
        visibleCount += 1;
      }
    });
    if (emptyMsg) {
      emptyMsg.hidden = visibleCount !== 0;
    }
  });
}

// ---------------------------------------------------------------------------
// Reading-progress bar (fills as the page is scrolled) + "Back to top" button
// (appears once the reader has scrolled past the hero). Present on every page.
// ---------------------------------------------------------------------------
function initScrollProgress() {
  const bar = document.getElementById('scroll-progress-bar');
  const backToTop = document.getElementById('back-to-top');

  function update() {
    const scrollTop = window.scrollY;
    const docHeight = document.documentElement.scrollHeight - window.innerHeight;
    const pct = docHeight > 0 ? Math.min(100, (scrollTop / docHeight) * 100) : 0;
    if (bar) {
      bar.style.width = `${pct}%`;
    }
    if (backToTop) {
      backToTop.hidden = scrollTop < 480;
    }
  }

  window.addEventListener('scroll', update, { passive: true });
  window.addEventListener('resize', update);
  update();

  backToTop?.addEventListener('click', () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });
}

// ---------------------------------------------------------------------------
// Day-card accordion (week1.html .. week5.html). First day starts open, the
// rest start collapsed -- click the day heading (or land on its anchor via a
// jump-nav / prev-next link / direct URL hash) to expand it.
// ---------------------------------------------------------------------------
function initDayAccordion() {
  const toggles = Array.from(document.querySelectorAll('.day-toggle'));
  if (!toggles.length) {
    return;
  }

  function setExpanded(toggle, expanded) {
    const body = document.getElementById(toggle.getAttribute('aria-controls'));
    if (!body) {
      return;
    }
    toggle.setAttribute('aria-expanded', expanded ? 'true' : 'false');
    body.hidden = !expanded;
  }

  toggles.forEach((toggle) => {
    toggle.addEventListener('click', () => {
      const isOpen = toggle.getAttribute('aria-expanded') === 'true';
      setExpanded(toggle, !isOpen);
    });
  });

  function expandFromHash() {
    const hash = window.location.hash.slice(1);
    if (!hash) {
      return;
    }
    const target = document.getElementById(hash);
    if (!target || !target.classList.contains('day-card')) {
      return;
    }
    const toggle = target.querySelector('.day-toggle');
    if (toggle && toggle.getAttribute('aria-expanded') !== 'true') {
      setExpanded(toggle, true);
    }
  }

  expandFromHash();
  window.addEventListener('hashchange', expandFromHash);
}

// ---------------------------------------------------------------------------
// Sticky "on this page" jump-nav: highlights the link for whichever section
// is currently in view, so the reader always knows where they are.
// ---------------------------------------------------------------------------
function initJumpNavScrollSpy() {
  const nav = document.querySelector('.jump-nav');
  if (!nav) {
    return;
  }
  const links = Array.from(nav.querySelectorAll('a[href^="#"]'));
  if (!links.length) {
    return;
  }
  const targets = links
    .map((link) => ({ link, el: document.getElementById(link.getAttribute('href').slice(1)) }))
    .filter((entry) => entry.el);

  if (!targets.length || typeof IntersectionObserver === 'undefined') {
    return;
  }

  function setActive(link) {
    links.forEach((candidate) => candidate.classList.toggle('active', candidate === link));
  }

  const observer = new IntersectionObserver(
    (entries) => {
      const visible = entries.filter((entry) => entry.isIntersecting);
      if (!visible.length) {
        return;
      }
      visible.sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
      const match = targets.find((entry) => entry.el === visible[0].target);
      if (match) {
        setActive(match.link);
      }
    },
    { rootMargin: '-15% 0px -70% 0px', threshold: 0 }
  );

  targets.forEach((entry) => observer.observe(entry.el));
}

// ---------------------------------------------------------------------------
// Visual Learning Studio tabs (index.html): swaps between the master
// flowchart and the GIF-style walkthrough instead of stacking both.
// ---------------------------------------------------------------------------
function initVisualsTabs() {
  const tabs = Array.from(document.querySelectorAll('.visuals-tab'));
  if (!tabs.length) {
    return;
  }
  tabs.forEach((tab) => {
    tab.addEventListener('click', () => {
      const targetId = tab.dataset.tabTarget;
      tabs.forEach((t) => {
        const isActive = t === tab;
        t.classList.toggle('active', isActive);
        t.setAttribute('aria-selected', isActive ? 'true' : 'false');
      });
      document.querySelectorAll('.visuals-tab-panel').forEach((panel) => {
        panel.hidden = panel.id !== targetId;
      });
    });
  });
}

// ---------------------------------------------------------------------------
// Milestone timeline (index.html): the numbered pins act as single-select
// buttons -- clicking one shows only that milestone's detail card instead of
// stacking all ~15 cards on the page at once.
// ---------------------------------------------------------------------------
function initMilestoneTabs() {
  const buttons = Array.from(document.querySelectorAll('.timeline-stop[data-milestone-target]'));
  if (!buttons.length) {
    return;
  }

  function activate(button, { scroll = false } = {}) {
    const targetId = button.dataset.milestoneTarget;
    buttons.forEach((b) => {
      const isActive = b === button;
      b.classList.toggle('active', isActive);
      b.setAttribute('aria-pressed', isActive ? 'true' : 'false');
    });
    document.querySelectorAll('.milestone-card').forEach((card) => {
      card.hidden = card.id !== targetId;
    });
    if (scroll) {
      document.getElementById(targetId)?.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  }

  buttons.forEach((button) => {
    button.addEventListener('click', () => activate(button, { scroll: true }));
  });

  function activateFromHash() {
    const hash = window.location.hash.slice(1);
    if (!hash) {
      return;
    }
    const button = buttons.find((b) => b.dataset.milestoneTarget === hash);
    if (button) {
      activate(button);
    }
  }

  activateFromHash();
  window.addEventListener('hashchange', activateFromHash);
}

// ---------------------------------------------------------------------------
// Scroll-reveal: top-level section panels fade/slide into place as they
// enter the viewport. Only applied to always-visible section panels (never
// to accordion/tab-controlled inner cards like .day-card or .milestone-card,
// since those toggle their own `hidden` attribute and would otherwise get
// stuck invisible if revealed while off-screen and hidden). Skips entirely
// under prefers-reduced-motion so motion-sensitive users just see the
// content, no animation.
function initScrollReveal() {
  const targets = Array.from(document.querySelectorAll('main#main-content > .panel'));
  if (!targets.length) {
    return;
  }

  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (prefersReducedMotion || typeof IntersectionObserver === 'undefined') {
    targets.forEach((target) => target.classList.add('is-visible'));
    return;
  }

  targets.forEach((target) => target.classList.add('reveal'));

  const observer = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          observer.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.1, rootMargin: '0px 0px -40px 0px' }
  );

  targets.forEach((target) => observer.observe(target));
}
