function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

// ---------------------------------------------------------------------------
// Lifecycle Walkthrough: Mermaid.js flow diagram + Next/Prev stepper.
// Data comes from the #lifecycle-data JSON script tag (only present on
// index.html), generated by build.py from the COURSE_LIFECYCLE list.
// ---------------------------------------------------------------------------
let lifecycleData = [];
let currentStep = 0;

function readLifecycleData() {
  const host = document.getElementById('lifecycle-data');
  if (!host) {
    return [];
  }
  try {
    return JSON.parse(host.textContent);
  } catch (error) {
    return [];
  }
}

// Extra "input" hand-offs called out explicitly in each day's `connects` text
// that skip ahead of the plain day-by-day sequence (for example, Day 4's
// pain points feed both Day 5 AND Week 2 Day 3's heuristic audit). Each entry
// is [fromWeekId, fromAnchor, toWeekId, toAnchor].
const LIFECYCLE_EXTRA_EDGES = [
  ['week1', 'd1', 'week2', 'd4'],
  ['week1', 'd2', 'week1', 'd4'],
  ['week1', 'd3', 'week3', 'd1'],
  ['week1', 'd4', 'week2', 'd3'],
  ['week2', 'd2', 'week3', 'd2'],
  ['week2', 'd3', 'week2', 'd5'],
  ['week2', 'd3', 'week3', 'd1'],
  ['week2', 'd4', 'week3', 'd1'],
  ['week2', 'd5', 'week3', 'd2'],
];

function findLifecycleIndex(weekId, anchor) {
  return lifecycleData.findIndex((day) => day.week_id === weekId && day.anchor === anchor);
}

function buildLifecycleEdges() {
  const edges = [];
  for (let idx = 0; idx < lifecycleData.length - 1; idx += 1) {
    edges.push([idx, idx + 1]);
  }
  LIFECYCLE_EXTRA_EDGES.forEach(([fromWeek, fromAnchor, toWeek, toAnchor]) => {
    const from = findLifecycleIndex(fromWeek, fromAnchor);
    const to = findLifecycleIndex(toWeek, toAnchor);
    if (from !== -1 && to !== -1) {
      edges.push([from, to]);
    }
  });
  return edges;
}

function buildMermaidDefinition(activeIndex) {
  const lines = ['flowchart TD'];
  lines.push('classDef w1 fill:#1a1b1e,stroke:#8a8f98,color:#f3f3f2;');
  lines.push('classDef w2 fill:#1e1213,stroke:#7a1218,color:#f3f3f2;');
  lines.push('classDef w3 fill:#22100f,stroke:#e2001a,color:#f3f3f2;');
  lines.push('classDef w4 fill:#1c1c1c,stroke:#f3f3f2,color:#f3f3f2;');
  lines.push('classDef activeStep stroke:#ff3b30,stroke-width:4px;');
  lines.push('classDef dimmed fill:#131315,stroke:#2b2b2f,color:#5a5a60;');

  const byWeek = {};
  lifecycleData.forEach((day, idx) => {
    if (!byWeek[day.week_id]) {
      byWeek[day.week_id] = [];
    }
    byWeek[day.week_id].push({ ...day, idx });
  });

  Object.keys(byWeek).forEach((weekId) => {
    const days = byWeek[weekId];
    lines.push(`subgraph ${weekId}_sg["${escapeHtml(days[0].week_label)} - ${escapeHtml(days[0].week_theme)}"]`);
    days.forEach((day) => {
      const nodeId = `N${day.idx + 1}`;
      const label = `${escapeHtml(day.week_label)} ${escapeHtml(day.day)}<br/>${escapeHtml(day.title)}`;
      lines.push(`${nodeId}["${label}"]`);
    });
    lines.push('end');
  });

  const edges = buildLifecycleEdges();
  edges.forEach(([from, to]) => {
    lines.push(`N${from + 1} --> N${to + 1}`);
  });

  // Only the active node's direct inputs (predecessors) and direct hand-offs
  // (successors) stay lit up; every other node/edge fades into the background.
  const litNodes = new Set([activeIndex]);
  const litEdgeIdxs = [];
  edges.forEach(([from, to], edgeIdx) => {
    if (from === activeIndex || to === activeIndex) {
      litNodes.add(from);
      litNodes.add(to);
      litEdgeIdxs.push(edgeIdx);
    }
  });

  Object.keys(byWeek).forEach((weekId) => {
    const litIds = byWeek[weekId].filter((day) => litNodes.has(day.idx)).map((day) => `N${day.idx + 1}`);
    const dimIds = byWeek[weekId].filter((day) => !litNodes.has(day.idx)).map((day) => `N${day.idx + 1}`);
    if (litIds.length) {
      lines.push(`class ${litIds.join(',')} ${weekId}`);
    }
    if (dimIds.length) {
      lines.push(`class ${dimIds.join(',')} dimmed`);
    }
  });

  lines.push(`class N${activeIndex + 1} activeStep`);

  const dimEdgeIdxs = edges.map((_, edgeIdx) => edgeIdx).filter((edgeIdx) => !litEdgeIdxs.includes(edgeIdx));
  if (dimEdgeIdxs.length) {
    lines.push(`linkStyle ${dimEdgeIdxs.join(',')} stroke:#2b2b2f,stroke-width:1px,opacity:0.3;`);
  }
  if (litEdgeIdxs.length) {
    lines.push(`linkStyle ${litEdgeIdxs.join(',')} stroke:#ff3b30,stroke-width:3px,opacity:1;`);
  }

  lifecycleData.forEach((_, idx) => {
    lines.push(`click N${idx + 1} lifecycleNodeClick`);
  });

  return lines.join('\n');
}

async function renderLifecycleDiagram() {
  const container = document.getElementById('lifecycle-mermaid');
  if (!container || !window.mermaid) {
    return;
  }
  const definition = buildMermaidDefinition(currentStep);
  try {
    const { svg, bindFunctions } = await window.mermaid.render('lifecycleGraph', definition);
    container.innerHTML = svg;
    if (bindFunctions) {
      bindFunctions(container);
    }
  } catch (error) {
    container.innerHTML = '<p>Diagram could not render.</p>';
  }
}

function renderStepperPanel(index) {
  const panel = document.getElementById('stepper-panel');
  if (!panel) {
    return;
  }
  const day = lifecycleData[index];
  if (!day) {
    return;
  }
  const artifactItems = (day.artifacts || []).map((a) => `<li>${escapeHtml(a)}</li>`).join('');

  panel.innerHTML = `
    <span class="day-kicker">${escapeHtml(day.week_label)} &middot; ${escapeHtml(day.day)}</span>
    <h3 class="stepper-panel-title">${escapeHtml(day.title)}</h3>
    <div class="day-block">
      <h4>What You Do</h4>
      <p>${escapeHtml(day.what)}</p>
    </div>
    <div class="day-block">
      <h4>Why We Do This</h4>
      <p>${escapeHtml(day.why)}</p>
    </div>
    <div class="day-block">
      <h4>Key Artifacts</h4>
      <ul class="day-artifacts">${artifactItems}</ul>
    </div>
    <div class="day-block day-connects">
      <h4>Connects To</h4>
      <p>${escapeHtml(day.connects)}</p>
    </div>
    <a class="stepper-link" href="${day.link}">Open ${escapeHtml(day.week_label)} Page &rarr;</a>
  `;
}

function updateStepper(index) {
  const total = lifecycleData.length;
  if (total === 0) {
    return;
  }
  currentStep = Math.max(0, Math.min(index, total - 1));

  const progressLabel = document.getElementById('stepper-progress-label');
  if (progressLabel) {
    progressLabel.textContent = `Step ${currentStep + 1} of ${total}`;
  }

  const prevBtn = document.getElementById('stepper-prev');
  const nextBtn = document.getElementById('stepper-next');
  if (prevBtn) {
    prevBtn.disabled = currentStep === 0;
  }
  if (nextBtn) {
    nextBtn.disabled = currentStep === total - 1;
  }

  renderStepperPanel(currentStep);
  renderLifecycleDiagram();
}

window.lifecycleNodeClick = function lifecycleNodeClick(nodeId) {
  const idx = parseInt(String(nodeId).replace('N', ''), 10) - 1;
  if (!Number.isNaN(idx)) {
    updateStepper(idx);
  }
};

function initLifecycleStepper() {
  const stepperHost = document.getElementById('lifecycle-stepper');
  lifecycleData = readLifecycleData();
  if (!stepperHost || lifecycleData.length === 0) {
    return;
  }

  if (window.mermaid) {
    window.mermaid.initialize({
      startOnLoad: false,
      securityLevel: 'loose',
      theme: 'base',
      themeVariables: {
        darkMode: true,
        background: '#0b0b0c',
        primaryColor: '#141416',
        primaryTextColor: '#f3f3f2',
        primaryBorderColor: '#2b2b2f',
        lineColor: '#8a8f98',
        secondaryColor: '#1b1b1e',
        tertiaryColor: '#1b1b1e',
        clusterBkg: '#101012',
        clusterBorder: '#2b2b2f',
        edgeLabelBackground: '#101012',
        fontFamily: 'Space Grotesk, Segoe UI, sans-serif',
      },
    });
  }

  const prevBtn = document.getElementById('stepper-prev');
  const nextBtn = document.getElementById('stepper-next');
  if (prevBtn) {
    prevBtn.addEventListener('click', () => updateStepper(currentStep - 1));
  }
  if (nextBtn) {
    nextBtn.addEventListener('click', () => updateStepper(currentStep + 1));
  }

  updateStepper(0);
}

// ---------------------------------------------------------------------------
// Source Scan Proof: renders the digest JSON into #source-summary and
// #syllabus-grid (index.html only).
// ---------------------------------------------------------------------------
async function loadSourceDigest() {
  const summaryHost = document.getElementById('source-summary');
  const syllabusHost = document.getElementById('syllabus-grid');

  if (!summaryHost || !syllabusHost) {
    return;
  }

  try {
    const response = await fetch('./data/course_source_digest.json');
    if (!response.ok) {
      throw new Error('Could not load source digest JSON.');
    }

    const digest = await response.json();
    const weekCount = digest.weeks.length;
    const dayCount = digest.weeks.reduce((acc, week) => acc + week.days.length, 0);
    const totalFiles = digest.totals.files_scanned;

    summaryHost.innerHTML = `
      <p><strong>Source Root:</strong> ${digest.root}</p>
      <p><strong>Method:</strong> Week-by-week and day-by-day scan of PDFs, DOCX, TXT, and HTML files.</p>
      <div class="source-kpis" role="list" aria-label="Source scan totals">
        <div class="source-kpi" role="listitem"><strong>${weekCount}</strong>Weeks Indexed</div>
        <div class="source-kpi" role="listitem"><strong>${dayCount}</strong>Days Indexed</div>
        <div class="source-kpi" role="listitem"><strong>${totalFiles}</strong>Files Read</div>
      </div>
    `;

    digest.weeks.forEach((week) => {
      const weekBlock = document.createElement('article');
      weekBlock.className = 'week-block';

      const topicSet = new Set();
      week.days.forEach((day) => {
        day.topics_detected.forEach((topic) => topicSet.add(topic));
      });

      const weekHead = document.createElement('div');
      weekHead.className = 'week-head';
      weekHead.innerHTML = `
        <h3>${week.week}</h3>
        <p>${week.days.length} days mapped | Topic spread: ${Array.from(topicSet).length}</p>
      `;

      const dayList = document.createElement('ul');
      dayList.className = 'day-list';

      week.days.forEach((day) => {
        const item = document.createElement('li');
        const chips = day.topics_detected.slice(0, 6).map((topic) => `<span class="chip">${topic}</span>`).join('');
        const keyArtifacts = (day.key_artifacts || []).map((name) => `<li>${name}</li>`).join('');
        const fileRefs = (day.files || []).slice(0, 8).map((entry) => `<li>${entry.file}</li>`).join('');
        item.innerHTML = `
          <h4>${day.day}</h4>
          <p class="day-meta">${day.file_count} readable files</p>
          <div class="topic-chips">${chips}</div>
          <details class="day-details">
            <summary>Open day drill-down</summary>
            <p><strong>Primary source:</strong> ${day.primary_source || 'N/A'}</p>
            <p><strong>Objective excerpt:</strong> ${day.objective_excerpt || 'Objective text not found in extracted source.'}</p>
            <p><strong>Key artifacts:</strong></p>
            <ul>${keyArtifacts || '<li>No artifact names captured.</li>'}</ul>
            <p><strong>File references:</strong></p>
            <ul class="file-ref-list">${fileRefs || '<li>No file references captured.</li>'}</ul>
          </details>
        `;
        dayList.appendChild(item);
      });

      weekBlock.appendChild(weekHead);
      weekBlock.appendChild(dayList);
      syllabusHost.appendChild(weekBlock);
    });
  } catch (error) {
    summaryHost.innerHTML = '<p><strong>Source digest could not be loaded.</strong> Run from localhost so JSON can be fetched, or review ./data/course_source_digest.md.</p>';
  }
}

initLifecycleStepper();
loadSourceDigest();
initSampleDialogs();
initSiteMenu();

// ---------------------------------------------------------------------------
// Site menu: hamburger toggle for the Core TPM Content / Technical Content
// dropdown in the header (present on every page via base.html).
// ---------------------------------------------------------------------------
function initSiteMenu() {
  const toggleBtn = document.getElementById('menu-toggle-btn');
  const menu = document.getElementById('site-menu');
  if (!toggleBtn || !menu) {
    return;
  }

  function closeMenu() {
    menu.dataset.open = 'false';
    toggleBtn.setAttribute('aria-expanded', 'false');
  }

  function openMenu() {
    menu.dataset.open = 'true';
    toggleBtn.setAttribute('aria-expanded', 'true');
  }

  toggleBtn.addEventListener('click', (event) => {
    event.stopPropagation();
    if (menu.dataset.open === 'true') {
      closeMenu();
    } else {
      openMenu();
    }
  });

  document.addEventListener('click', (event) => {
    if (menu.dataset.open === 'true' && !menu.contains(event.target) && event.target !== toggleBtn) {
      closeMenu();
    }
  });

  document.addEventListener('keydown', (event) => {
    if (event.key === 'Escape') {
      closeMenu();
    }
  });
}

// ---------------------------------------------------------------------------
// Milestone "View Filled Sample" dialogs (index.html only). Opens the native
// <dialog> that matches the clicked button's data-open-dialog id, closes on
// the close button, the Escape key (native), or a click on the backdrop.
// ---------------------------------------------------------------------------
function initSampleDialogs() {
  document.addEventListener('click', (event) => {
    const opener = event.target.closest('[data-open-dialog]');
    if (opener) {
      const dialog = document.getElementById(opener.dataset.openDialog);
      if (dialog && typeof dialog.showModal === 'function') {
        dialog.showModal();
      }
      return;
    }
    const closer = event.target.closest('[data-close-dialog]');
    if (closer) {
      closer.closest('dialog')?.close();
    }
  });

  document.querySelectorAll('dialog.sample-dialog').forEach((dialog) => {
    dialog.addEventListener('click', (event) => {
      if (event.target === dialog) {
        dialog.close();
      }
    });
  });
}
